# This file contains values from Cookiecutter

default_context:
  project_name: "alpha_connector"
  project_description: "Awesome `alpha_connector` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "alpha_connector"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "AlphaConnector"
  email: "hello@alpha_connector.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
